[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = "0.7"
rspc-procedure = "0.0.1"
rspc-axum = "0.3.0"
tower-http = { version = "0.5", features = ["cors"] }
tokio-rusqlite = { version = "0.7", features = ["bundled"] }
rusqlite = { version = "0.37", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
reqwest = { version = "0.12", features = ["json"] }
